SELECT PATHS 
FROM NANOPARTICLEANALYSISRESULTS
WHERE NAME = 'Wendy Ji'
UNION
SELECT PATHS 
FROM BINDINGANALYSISRESULTS
WHERE NAME = 'Wendy Ji';



SELECT C.NAME, COUNT(UNIQUE(CRID)) AS NUMBEROFDATA
FROM CLICDASHBOARD C, LABMEMBER L
WHERE C.DATES >= '2019-01-01' AND C.DATES <= '2019-02-28' AND C.NAME = L.NAME AND L.STATUS='active'
GROUP BY C.NAME
ORDER BY NUMBEROFDATA;

                            
-- Q9 Analytics
SELECT M.NAME, M.NUMEBRDATA, N.NUMEBRDATA, ROUND(CAST(M.NUMEBRDATA AS DOUBLE)/N.NUMEBRDATA,3) 
FROM
(SELECT Y.NAME, COUNT(X.CRID) AS NUMEBRDATA 
FROM 
(SELECT UNIQUE(D.CRID) AS CRID FROM CLICDASHBOARD D, CLICRAWDATA R
WHERE D.CRID = R.CRID AND D.FOCUS > 3) X, LABMEMBER Y, EXPERIMENT Z
WHERE Y.STATUS = 'active' AND Z.CRID = X.CRID AND Y.NAME = Z.NAME
GROUP BY Y.NAME
ORDER BY NUMEBRDATA)M,
(SELECT Y.NAME, COUNT(X.CRID) AS NUMEBRDATA
FROM 
(SELECT UNIQUE(D.CRID) AS CRID FROM CLICDASHBOARD D, CLICRAWDATA R
WHERE D.CRID = R.CRID ) X, LABMEMBER Y, EXPERIMENT Z
WHERE Y.STATUS = 'active' AND Z.CRID = X.CRID AND Y.NAME = Z.NAME
GROUP BY Y.NAME
ORDER BY NUMEBRDATA)N
WHERE M.NAME=N.NAME
                            
                            
                            

SELECT PATHS 
FROM DNAUNWINDINGDATA D, BINDINGANALYSISRESULTS B
WHERE D.CRID=B.CRID AND (B.ANALYSISTYPE IN ('decent','accurate'));


                                            
SELECT DISTINCT P.PATHS
FROM PROTOCOL P, EXPERIMENT E, NANOPARTICLEANALYSISRESULTS N
WHERE N.CRID = E.CRID AND N.AVGRADIUS > 40 AND E.PROTOCOLID=P.PROTOCOLID AND E.TRYNUMBER >= 2; 
                                            
                                            
-- Q9 Analytics
SELECT RNAME, RANAME, AVGFOCUS, AVGSNR, AVGCONT, NBCRID
FROM
(SELECT *
FROM SUPERVISE S
INNER JOIN
(SELECT NAME, AVG(FOCUS) AS AVGFOCUS, AVG(SNR) AS AVGSNR, AVG(CONTAMINANTS) AS AVGCONT, COUNT(DISTINCT CRID) AS NBCRID
FROM CLICDASHBOARD
WHERE YEAR(DATES)-YEAR(CURRENT DATE) < 2
GROUP BY NAME)
ON NAME=S.RANAME) A, LABMEMBER L
WHERE A.RANAME=L.NAME AND L.STATUS='active'
ORDER BY RNAME, RANAME;

