-- 6.1
UPDATE LABMEMBER 
SET STATUS = CASE 
WHEN NAME IN ('Stone Chen','Wendy Ji') THEN 'inactive' 
ELSE STATUS
END;

UPDATE SUPERVISE S
SET ENDDATE = NULL
WHERE RANAME ='Wendy Ji' OR RANAME ='Stone Chen';

UPDATE SUPERVISE S
SET ENDDATE = '2019-05-01'
WHERE EXISTS 
(SELECT L.NAME
FROM LABMEMBER L
WHERE L.STATUS = 'inactive' AND L.NAME=S.RANAME AND S.ENDDATE IS NULL);



-- 6.2
INSERT INTO LABMEMBER
VALUES ('Raffle Zhu','(514)-888-8888','active');

INSERT INTO RESEARCHASSISTANT
VALUES ('Raffle Zhu');

INSERT INTO SUPERVISE (STARTDATE, RNAME, RANAME)
VALUES ('2019-04-01', (SELECT RNAME FROM SUPERVISE WHERE RANAME='Stone Chen'), 'Raffle Zhu');



-- 6.3
UPDATE BINDINGANALYSISRESULTS
SET ANALYSISTYPE = 'decent'
WHERE NAME='Zhi Zhang' AND ANALYSISTYPE = 'rough';



-- 6.4
INSERT INTO CLICDASHBOARD(DID,DATES,PATHS,FOCUS,SNR,CONTAMINANTS,CRID,NAME) VALUES
(201,'2016-03-03','C:\CLiCDashBoard\201',1,0.67,5000,115,'Stone Chen'),
(202,'2016-03-03','C:\CLiCDashBoard\202',4,3.14,1000,115,'Stone Chen');

DELETE FROM CLICDASHBOARD
WHERE FOCUS < 2 OR (YEAR(CURRENT DATE)-YEAR(DATES)) > 1;  
