DROP VIEW SOMENAME;

CREATE VIEW SOMENAME (NAME) AS
SELECT B.NAME 
FROM BINDINGANALYSISRESULTS B, SUPERVISE S, LABMEMBER L
WHERE B.NAME = S.RANAME AND YEAR(S.STARTDATE) >= 2018 AND B.NAME = L.NAME AND L.STATUS = 'active'
UNION ALL
SELECT N.NAME
FROM NANOPARTICLEANALYSISRESULTS N, SUPERVISE S, LABMEMBER L
WHERE N.NAME = S.RANAME AND YEAR(S.STARTDATE) >= 2018 AND N.NAME = L.NAME AND L.STATUS = 'active';

SELECT * FROM SOMENAME;
SELECT NAME,COUNT(*) AS NUMBERDA
FROM SOMENAME
GROUP BY NAME
ORDER BY NUMBERDA;

UPDATE SOMENAME SET NAME = 'Yunwen Ji' WHERE NAME = 'Wendy Ji';





DROP VIEW MICROSCOPECONDITIONS;

CREATE VIEW MICROSCOPECONDITIONS (MICROID,NUMBERUSED) AS
SELECT MICROSCOPEID,COUNT(*) AS NUMBERUSED 
FROM
(SELECT E.MICROSCOPEID 
FROM EXPERIMENT E, MICROSCOPE M
WHERE  E.MICROSCOPEID = M.MICROSCOPEID AND M.STATUS = 'active')T
GROUP BY MICROSCOPEID
;

SELECT * FROM MICROSCOPECONDITIONS;
UPDATE MICROSCOPECONDITIONS SET NUMBERUSED = 0 WHERE MICROID = 'Nikon01';

UPDATE MICROSCOPE M
SET M.STATUS = 'inactive'
WHERE EXISTS 
(SELECT *
FROM MICROSCOPECONDITIONS C
WHERE C.NUMBERUSED >= 1000);
