ALTER TABLE BINDINGANALYSISRESULTS 
ADD CONSTRAINT DATE_check CHECK (YEAR(DATES) >= 2018);

ALTER TABLE BINDINGANALYSISRESULTS 
DROP CONSTRAINT DATE_check;

ALTER TABLE LABMEMBER 
ADD CONSTRAINT NUMBER_check CHECK (CONTACTINFORMATION LIKE '(%)-%-%');

ALTER TABLE LABMEMBER 
DROP CONSTRAINT NUMBER_check;
